name: 'Show neofetch'
description: 'Display system info using neofetch'

branding:
  icon: 'align-left'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch | bash -s -- --config ${{ github.action_path }}/config.conf
      shell: bash
